---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
collections:
  _projects:
    default_front_matter_template: project
  _people:
    default_front_matter_template: person
  _posts:
    default_front_matter_template: post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
